import type { EditorThemeClasses } from "lexical";

export const theme: EditorThemeClasses = {
  autocomplete: "",
  blockCursor: "",
  characterLimit: "",
  code: "",
  embedBlock: {
    base: "",
    focus: "",
  },
  hashtag: "",
  heading: {
    h1: "",
    h2: "",
    h3: "",
    h4: "",
    h5: "",
    h6: "",
  },
  hr: "",
  image: "editor-image",
  indent: "",
  inlineImage:
    "inline-editor-image relative !my-2 min-w-1/2 bg-white border rounded-md shadow-sm",
  layoutContainer: "",
  layoutItem: "",
  link: "",
  list: {
    checklist: "",
    listitem: "!my-0",
    listitemChecked: "",
    listitemUnchecked: "",
    nested: {
      listitem: "",
    },
    olDepth: ["list-decimal", "", "", "", ""],
    ul: "list-disc !ps-4",
    ol: "list-decimal !ps-5",
  },
  ltr: "",
  mark: "",
  markOverlap: "",
  paragraph: "!m-0 relative",
  quote: "border-l-8 border-cyan-200",
  rtl: "",
  table: "",
  tableCell: "",
  tableCellActionButton: "",
  tableCellActionButtonContainer: "",
  tableCellEditing: "",
  tableCellHeader: "",
  tableCellPrimarySelected: "",
  tableCellResizer: "",
  tableCellSelected: "",
  tableCellSortedIndicator: "",
  tableResizeRuler: "",
  tableSelected: "",
  tableSelection: "",
  text: {
    bold: "",
    code: "",
    italic: "",
    strikethrough: "line-through",
    subscript: "",
    superscript: "",
  },
};
