export function getRandomAnimal() {
  const animal = animals[Math.floor(Math.random() * animals.length)];
  const [animalName, emoji] = animal;
  const firstLetter = animalName.substring(0, 1) as keyof typeof adjectives;
  const adjective =
    adjectives[firstLetter][
      Math.floor(Math.random() * adjectives[firstLetter].length)
    ];
  const color = colors[Math.floor(Math.random() * colors.length)];
  const name = `${adjective} ${animalName}`;
  return { name, emoji, color };
}

const animals = [
  ["Badger", "🦡"],
  ["Bat", "🦇"],
  ["Bear", "🐻"],
  ["Beaver", "🦫"],
  ["Bird", "🐦"],
  ["Bison", "🦬"],
  ["Boar", "🐗"],
  ["Buffalo", "🐃"],
  ["Camel", "🐫"],
  ["Cat", "🐱"],
  ["Chicken", "🐔"],
  ["Chipmunk", "🐿"],
  ["Cow", "🐮"],
  ["Crab", "🦀"],
  ["Cricket", "🦗"],
  ["Crocodile", "🐊"],
  ["Deer", "🦌"],
  ["Dodo", "🦤"],
  ["Dog", "🐶"],
  ["Dolphin", "🐬"],
  ["Duck", "🦆"],
  ["Eagle", "🦅"],
  ["Elephant", "🐘"],
  ["Fish", "🐠"],
  ["Flamingo", "🦩"],
  ["Fox", "🦊"],
  ["Frog", "🐸"],
  ["Giraffe", "🦒"],
  ["Goat", "🐐"],
  ["Gorilla", "🦍"],
  ["Hamster", "🐹"],
  ["Hedgehog", "🦔"],
  ["Hippo", "🦛"],
  ["Honeybee", "🐝"],
  ["Horse", "🐴"],
  ["Kangaroo", "🦘"],
  ["Koala", "🐨"],
  ["Ladybug", "🐞"],
  ["Leopard", "🐆"],
  ["Lion", "🦁"],
  ["Lizard", "🦎"],
  ["Llama", "🦙"],
  ["Lobster", "🦞"],
  ["Mammoth", "🦣"],
  ["Monkey", "🐵"],
  ["Mouse", "🐭"],
  ["Orangutan", "🦧"],
  ["Otter", "🦦"],
  ["Owl", "🦉"],
  ["Panda", "🐼"],
  ["Parrot", "🦜"],
  ["Peacock", "🦚"],
  ["Penguin", "🐧"],
  ["Pig", "🐷"],
  ["Poodle", "🐩"],
  ["Rabbit", "🐰"],
  ["Raccoon", "🦝"],
  ["Ram", "🐏"],
  ["Rhino", "🦏"],
  ["Rooster", "🐓"],
  ["Sauropod", "🦕"],
  ["Scorpion", "🦂"],
  ["Seal", "🦭"],
  ["Shark", "🦈"],
  ["Sheep", "🐑"],
  ["Shrimp", "🦐"],
  ["Skunk", "🦨"],
  ["Sloth", "🦥"],
  ["Snake", "🐍"],
  ["Swan", "🦢"],
  ["Tiger", "🐯"],
  ["Turkey", "🦃"],
  ["Turtle", "🐢"],
  ["Whale", "🐳"],
  ["Wolf", "🐺"],
  ["Zebra", "🦓"],
] as const;

const adjectives = {
  B: [
    "Beautiful",
    "Believable",
    "Beloved",
    "Benevolent",
    "Best",
    "Better",
    "Blissful",
    "Booming",
    "Brainy",
    "Brave",
    "Breathtaking",
    "Bright",
    "Brilliant",
    "Brotherly",
  ],
  C: [
    "Calm",
    "Captivating",
    "Carefree",
    "Charismatic",
    "Charming",
    "Cheerful",
    "Classy",
    "Clear",
    "Clever",
    "Colorful",
    "Comfy",
    "Confident",
    "Considerate",
    "Convenient",
    "Convincing",
    "Cool",
    "Cooperative",
    "Courageous",
    "Cozy",
    "Creative",
    "Credible",
    "Cushy",
    "Cute",
  ],
  D: [
    "Daring",
    "Dashing",
    "Dazzling",
    "Decisive",
    "Dedicated",
    "Deft",
    "Delightful",
    "Dependable",
    "Diligent",
    "Diplomatic",
    "Diplomatic",
    "Disarming",
    "Dreamy",
    "Dynamic",
  ],
  E: [
    "Eager",
    "Earnest",
    "Easygoing",
    "Ecstatic",
    "Educated",
    "Elegant",
    "Eloquent",
    "Enchanting",
    "Energetic",
    "Engaging",
    "Enjoyable",
    "Enterprising",
    "Entertaining",
    "Enthusiastic",
    "Enticing",
    "Entranced",
    "Entrancing",
    "Euphoric",
    "Excellent",
    "Exceptional",
    "Excited",
    "Exquisite",
    "Extraordinary",
  ],
  F: [
    "Fabulous",
    "Fair",
    "Fancy",
    "Fantastic",
    "Fascinating",
    "Faster",
    "Favorite",
    "Fearless",
    "Feisty",
    "Festive",
    "Fiery",
    "Fine",
    "Flashy",
    "Flattering",
    "Flourishing",
    "Formidable",
    "Fortunate",
    "Friendly",
    "Frugal",
    "Fruitful",
    "Funny",
    "Futuristic",
  ],
  G: [
    "Generous",
    "Genial",
    "Gentle",
    "Genuine",
    "Gifted",
    "Glamorous",
    "Gleeful",
    "Glimmering",
    "Glistening",
    "Glowing",
    "Good",
    "Graceful",
    "Gracious",
    "Grateful",
    "Great",
    "Gutsy",
  ],
  H: [
    "Handsome",
    "Handy",
    "Happy",
    "Hardy",
    "Harmonious",
    "Healthy",
    "Heartwarming",
    "Helpful",
    "High-spirited",
    "Hilarious",
    "Honest",
    "Honored",
    "Hopeful",
    "Hospitable",
    "Humble",
    "Humorous",
  ],
  K: [
    "Keen",
    "Kempt",
    "Kind",
    "Kindhearted",
    "Kindly",
    "Kingly",
    "Knowledgeable",
  ],
  L: [
    "Laudable",
    "Legendary",
    "Light-hearted",
    "Likable",
    "Lively",
    "Logical",
    "Lovely",
    "Loving",
    "Loyal",
    "Lucky",
    "Lyrical",
  ],
  M: [
    "Magical",
    "Magnificent",
    "Marvelous",
    "Memorable",
    "Merciful",
    "Merry",
    "Mesmerizing",
    "Meticulous",
    "Mighty",
    "Mind-blowing",
    "Miraculous",
    "Modest",
    "Motivated",
  ],
  O: [
    "Observant",
    "Open",
    "Optimistic",
    "Organized",
    "Outspoken",
    "Outstanding",
    "Overjoyed",
  ],
  P: [
    "Palmy",
    "Passionate",
    "Patient",
    "Peaceful",
    "Peachy",
    "Peppy",
    "Perceptive",
    "Perky",
    "Poetic",
    "Polite",
    "Priceless",
    "Productive",
    "Purposeful",
  ],
  R: [
    "Radiant",
    "Rapid",
    "Rational",
    "Ready",
    "Reasonable",
    "Receptive",
    "Refined",
    "Rejoicing",
    "Relaxed",
    "Reliable",
    "Remarkable",
    "Renowned",
    "Resilient",
    "Resolute",
    "Resourceful",
    "Respectable",
    "Respectful",
  ],
  S: [
    "Self-sufficient",
    "Sensational",
    "Sensible",
    "Serene",
    "Sharp",
    "Shiny",
    "Skillful",
    "Sleek",
    "Slick",
    "Smart",
    "Smiling",
    "Smooth",
    "Snappy",
    "Snazzy",
    "Solid",
    "Sophisticated",
    "Soulful",
    "Spirited",
    "Splendid",
    "Spontaneous",
    "Striking",
    "Strong",
    "Stunning",
    "Stylish",
    "Suave",
    "Sublime",
    "Successful",
    "Superb",
    "Supportive",
    "Swanky",
    "Sweeping",
    "Swift",
  ],
  T: [
    "Talented",
    "Tantalizing",
    "Tenacious",
    "Tender",
    "Terrific",
    "Thankful",
    "Thoughtful",
    "Thrifty",
    "Thrilled",
    "Trendy",
    "Trouble-free",
    "Trusty",
    "Truthful",
    "Twinkly",
  ],
  W: [
    "Warmhearted",
    "Well-informed",
    "Well-known",
    "Wholesome",
    "Winning",
    "Wise",
    "Witty",
    "Wonderful",
    "Wondrous",
  ],
  Z: [
    "Zany",
    "Zappy",
    "Zazzy",
    "Zealous",
    "Zeitgeisty",
    "Zen",
    "Zesty",
    "Zingy",
    "Zippy",
    "Zooming",
    "Zooty",
  ],
} as const;

// tailwind 200er colors
export const colors = [
  "#fca5a5",
  "#fdba74",
  "#fcd34d",
  "#fde047",
  "#bef264",
  "#86efac",
  "#67e8f9",
  "#7dd3fc",
  "#93c5fd",
  "#a5b4fc",
  "#c4b5fd",
  "#d8b4fe",
  "#f0abfc",
  "#f9a8d4",
];
